name: Build project

on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - '*'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: 'x64'

      - name: Build & Test
        run: mvn -B clean package

      - name: create & run docker image
        run: make doc